#!/bin/bash

# Daniel M. Lofaro (dan@danlofaro.com)
sudo ls > /dev/null



export LD_LIBRARY_PATH=/usr/lib:
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"


SHOKO_STATE_CHAN='shoko-state'
SHOKO_REF_CHAN='shoko-ref'
SHOKO_NAMESPACE='shoko'
FLAG_REMOTE=0
SHOKO_PYTHON_DIR='./'
MDS_REMOTE_ADDRESS='0.0.0.0'

trim()
{
  local var=$@
  echo -n "${var//[[:space:]]/}"
}


MakeAch()
{
	ach -1 mk $SHOKO_REF_CHAN -m 10 -n 3000
	ach -1 mk $SHOKO_STATE_CHAN
        sudo chmod 777 /dev/shm/achshm-$SHOKO_NAMESPACE*
}

KillAch()
{
        sudo rm -rf /dev/shm/achshm-$SHOKO_NAMESPACE*
}


KillAll()
{
  Kill
  KillAch
  KillRemote
  KillSim
}

KillSim()
{
  sudo kill -9 $(pidof gzclient)
  sudo kill -9 $(pidof gzserver)
}

Kill()
{
  echo ' '
}

Remote()
{

case "$1" in 
'kill')
	KillRemote
;;
*)
	MakeAch
	achd -r push $1 $SHOKO_REF_CHAN &
	achd -r pull $1 $SHOKO_STATE_CHAN &
	achd -r pull $1 $SHOKO_PARAM_CHAN &
	achd -r push $1 $SHOKO_CMD_CHAN &

;;
esac

}


KillRemote()
{
	sudo kill -9 $(pidof achd)
}



ShowUsage()
{
	echo
	echo 'start         : Start all channels and processes and consle'
	echo 'stop          : Close all channels and processes'
        echo 'make          : Makes all the SHOKO channels'
	echo 'remote        : Starts a remote connection to xxx.xxx.xxx.xxx via achd'
	echo '		    : Options:'
	echo '              :     (no-arg)   : Starts remote connections'
	echo '              :     kill       : Kills remote connection'
	echo
}


Console()
{
  python $MDS_PYTHON_DIR/mds_console.py read
}

Read()
{
  python $MDS_PYTHON_DIR/mds_read.py read
}


Start()
{
  MakeAch

  DAEMON_ARGS=''

  nohup python $SHOKO_PYTHON_DIR/shokod.py >> /dev/null #& echo $! >> $MDS_HOME_DIR/$MDS_PID_FILE
#  screen -S mdsik -d -m mds_ik_module.py
}

SetFlags()
{
MDS_I=0
MDS_TEMP1="$@"
MDS_TEMP=($MDS_TEMP1)
for var in "$@"
do
#    echo "$var"
    case "$var" in
      'remote' )
	  FLAG_REMOTE=1
          SHOKO_REMOTE_ADDRESS=${MDS_TEMP[$(($MDS_I+1))]}
	  echo "Remote address set: "$MDS_REMOTE_ADDRESS
      ;;
    esac
    MDS_I=$(($MDS_I+1))

done
}



SetFlags $@
case "$1" in
# Start all channels and processes
	'make' )
		MakeAch $@
	;;

# Start all channels and processes and Console
	'start' )
		Start $@
	;;

# Start remote via achd
	'remote' )
		Remote $2
	;;

# Kill all hubo processies and remove ach
	'killall' )
		KillAll
	;;

# Emergency kill
	'kill' )
		Kill $2
	;;

	*)
		ShowUsage
		exit 1
	;;
esac

exit 0

# Local Variables:
#  indent-tabs-mode:t
#  tab-width: 8
#  c-basic-offset: 8
# End:
