#!/bin/bash
sudo su - hubo
screen -S shoko-daemon-ros -dm bash -c 'source /opt/ros/kinetic/setup.bash; source /home/hubo/ros_ws/devel/setup.sh; sleep 5; python /home/hubo/projects/shoko-ach/shokod_ros.py'
